name: test_2_basic_normal
on:
  push:
    paths:
      - '.github/workflows/2_basic_normal.yml'
  pull_request:
    paths:
      - '.github/workflows/2_basic_normal.yml'
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: |
          echo "Hello, World!"
          echo "${{ github.run_id }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
          echo "${{ github.repository_owner }}"
          echo "${{ github.event }}"
          git log -1
