name: test_2_basic_by_hand
on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input'
        required: true
        default: 'goodbye'
jobs:
  hand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Say Hello
        run: |
          echo "Hello, World!"
          echo "${{ inputs.example_input }}"
