name: 2_basic_by_time
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Say Hello
        run: |
          echo "Hello, World!"
          date
