name: test_3_basic_values
on: [push]
jobs:
  values:
    name: printing values
    runs-on: ubuntu-latest
    env:
      ENV_NAME: example_value
      REPO_NAME: ${{github.repository}}
      REPO_VAL_QWERT: ${{vars.VAL_QWERT_12345}}

    steps:
      - uses: actions/checkout@v4
      - name: Say github and runner info
        run: |
          echo "Hello, World!"
          echo "${{ github.run_id }}"
          echo "${{ github.head_ref }}"
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
          echo "${{ github.repository_owner }}"
          echo "${{ github.event }}"
          echo "${{ runner.name }}"
          echo "${{ runner.os }}"
          echo "${{ runner.arch }}"
          echo "${{ runner.temp }}"
          echo "${{ runner.tool_cache }}"
          echo "${{ runner.debug }}"

      - name: show env value
        run: |
          echo "The value of ENV_NAME is $ENV_NAME"
          echo "${{env.REPO_NAME}}"
          echo "${{env.REPO_VAL_QWERT}}"

      - name: default github value
        run: |
          echo "${GITHUB_ACTION}"
          echo "${GITHUB_REPOSITORY}"

      - name: compare
        run: |
          echo "${{ contains(github.repository, env.REPO_NAME) }}"
          echo "${{ startsWith(github.repository, 'train') }}"
          echo "${{ endsWith(github.repository, 'cicd') }}"

      - name: if_check
        if: ${{ contains(github.repository, env.REPO_NAME) && success() }}
        run: |
          echo "if checks done"

      - name: export values
        id: source
        run: |
          echo "result=success" >> $GITHUB_OUTPUT
      - name: use exported values
        env:
          RESULT_VAL: ${{ steps.source.outputs.result }}
        run: |
          echo "The exported value is '${RESULT_VAL}'"