name: test_4_cicd
on:
  push:
    paths:
      - './scripts/*.py'
      - '.github/workflows/4_cicd.yml'
  pull_request:
    paths:
      - './scripts/*.py'
      - '.github/workflows/4_cicd.yml'
    # paths-ignore:
    #   - 'README.md'
    # branches:
    #   - main
    # branches-ignore:
    #   - develop
    # tags:
    #   - '*'
    # tags-ignore:
    #   - 'v*.*.*'
concurrency: ${{ github.workflow }}
jobs:
  test:
    name: execute test scripts
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
      contents: read
    env:
      ENV_NAME: example_value

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest ./test/test_even_or_odd.py

      - name: Run linter
        run: |
          pip install flake8
          flake8 ./scripts/ --max-line-length=100
