name: test_4_cicd
on:
  push:
    paths:
      - './scripts/*.py'
      - '.github/workflows/4_cicd.yml'
  pull_request:
    # paths:
    #   - './scripts/*.py'
    # paths-ignore:
    #   - 'README.md'
    # branches:
    #   - main
    # branches-ignore:
    #   - develop
    # tags:
    #   - '*'
    # tags-ignore:
    #   - 'v*.*.*'
concurrency: ${{ github.workflow }}
jobs:
  test1:
    name: execute test scripts
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write
      contents: read
    env:
      ENV_NAME: example_value

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest ./test/test_even_or_odd.py

      - name: Run linter
        run: |
          pip install flake8
          flake8 ./scripts/ --max-line-length=100

      - name: Debug log
        run: |
          echo "::debug::This is a debug message"
          echo "::group::Grouped Logs"
          echo "This is inside a log group"
          echo "::endgroup::"
          echo "::error::This is an error message"
          echo "::warning::This is a warning message"
          echo "::notice::This is a notice message"

      - name: Upload test summary
        run: |
          echo "# Test Summary" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"

      - id: generate_output
        name: Generate output
        run: |
          echo "output_value=42" >> "$GITHUB_OUTPUT"

    outputs:
      my_output: ${{ steps.generate_output.outputs.output_value }}

  test2:
    name: execute second job
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "This is second job."

  test3:
    name: execute third job
    runs-on: ubuntu-latest
    needs: test1
    steps:
      - name: Echo message
        run: echo "This is third job that runs after the first job."

      - env:
          FIRST_JOB_OUTPUT: ${{ needs.test1.outputs.my_output }}
        name: Use output from first job
        run: |
          echo "Output from first job: $FIRST_JOB_OUTPUT"

  upload:
    name: Upload artifact
    runs-on: ubuntu-latest
    needs: [test1, test2, test3]
    steps:
      - uses: actions/checkout@v4

      - env:
          FIRST_JOB_OUTPUT: ${{ needs.test1.outputs.my_output }}
        name: Use output from first job
        run: |
          echo "Output from first job: $FIRST_JOB_OUTPUT"

      - name: Create a file to upload
        run: |
          echo "This is a sample artifact file." >> artifact.txt
          echo "Output from first job: $FIRST_JOB_OUTPUT" >> artifact.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sample-artifact
          path: artifact.txt
          retention-days: 5

  download:
    name: Download artifact
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sample-artifact
          path: ./downloaded-artifact
      - run: |
          cat ./downloaded-artifact/artifact.txt