name: test_6_module_usage
on:
  push:
    paths:
      - '.github/workflows/6_useactions.yml'
      - '.github/actions/6_module/*'
  pull_request:
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Dump Module
        uses: ./.github/actions/6_module
        id: dump_module
        with:
          enable-context: 'true'

      - name: Show Dumped Date
        run: echo "Dumped Date "${DATE}"
        env:
          DATE: ${{ steps.dump_module.outputs.dumped-date }}"